name: Docker Publish

on:
  schedule:
    - cron: 0 20 * * *

  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for SQLite image
        id: meta-sqlite
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,latest
            type=raw,sqlite
            type=ref,event=branch,suffix=-sqlite

      - name: Build and push SQLite Docker image
        id: build-and-push-sqlite
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-sqlite.outputs.tags }}
          labels: ${{ steps.meta-sqlite.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Extract Docker metadata for MySQL image
        id: meta-mysql
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,mysql
            type=ref,event=branch,suffix=-mysql

      - name: Build and push MySQL Docker image
        id: build-and-push-mysql
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            EXTRA_PIP_INSTALL_ARGS=mysqlclient
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-mysql.outputs.tags }}
          labels: ${{ steps.meta-mysql.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
